export const categories = [
  "Fashion & Accessories",
  "Electronics & Technology",
  "Home & Living",
  "Furniture & Decor",
  "Health & Personal Care",
  "Food & Groceries",
  "Industrial & Machinery",
  "Sports & Outdoor",
  "Automotive & Transportation",
  "Office & Education",
  "Arts, Media & Entertainment",
  "Baby & Kids",
  "Pets",
  "Construction & Raw Materials",
  "Other",
];
