export const categories = [
  "Art & Craft",
  "Automotive Parts",
  "Baby Products",
  "Bags & Luggage",
  "Bicycles",
  "Books",
  "Building Materials",
  "Camping Gear",
  "Cleaning Supplies",
  "Clothing",
  "Cosmetics",
  "Documents",
  "Electronics",
  "Energy Equipment",
  "Fishing Equipment",
  "Food & Beverages",
  "Footwear",
  "Garden & Outdoor",
  "Groceries",
  "Health & Wellness",
  "Home Appliances",
  "Jewelry",
  "Machinery",
  "Medical Supplies",
  "Musical Instruments",
  "Office Supplies",
  "Other",
  "Pet Supplies",
  "Pharmaceuticals",
  "Raw Materials",
  "Safety Equipment",
  "Sports Equipment",
  "Stationery",
  "Tools & Hardware",
  "Toys & Games",
];
