export const countries = [
  "Afghanistan",
  "Algeria",
  "Andorra",
  "Angola",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Bolivia",
  "Botswana",
  "Brazil",
  "Bulgaria",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Estonia",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Guatemala",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Lebanon",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Malaysia",
  "Malta",
  "Mexico",
  "Monaco",
  "Mongolia",
  "Morocco",
  "Myanmar",
  "Namibia",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "San Marino",
  "Saudi Arabia",
  "Serbia",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Thailand",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "UAE",
  "Ukraine",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Zimbabwe",
];

// Country to phone code mapping
export const countryPhoneCodes: { [key: string]: string } = {
  "Afghanistan": "+93",
  "Algeria": "+213",
  "Andorra": "+376",
  "Angola": "+244",
  "Argentina": "+54",
  "Armenia": "+374",
  "Australia": "+61",
  "Austria": "+43",
  "Azerbaijan": "+994",
  "Bahamas": "+1242",
  "Bangladesh": "+880",
  "Barbados": "+1246",
  "Belarus": "+375",
  "Belgium": "+32",
  "Bolivia": "+591",
  "Botswana": "+267",
  "Brazil": "+55",
  "Bulgaria": "+359",
  "Cambodia": "+855",
  "Cameroon": "+237",
  "Canada": "+1",
  "Chile": "+56",
  "China": "+86",
  "Colombia": "+57",
  "Costa Rica": "+506",
  "Croatia": "+385",
  "Cuba": "+53",
  "Cyprus": "+357",
  "Czech Republic": "+420",
  "Denmark": "+45",
  "Dominican Republic": "+1809",
  "Ecuador": "+593",
  "Egypt": "+20",
  "El Salvador": "+503",
  "Estonia": "+372",
  "Ethiopia": "+251",
  "Fiji": "+679",
  "Finland": "+358",
  "France": "+33",
  "Georgia": "+995",
  "Germany": "+49",
  "Ghana": "+233",
  "Greece": "+30",
  "Guatemala": "+502",
  "Honduras": "+504",
  "Hungary": "+36",
  "Iceland": "+354",
  "India": "+91",
  "Indonesia": "+62",
  "Ireland": "+353",
  "Israel": "+972",
  "Italy": "+39",
  "Ivory Coast": "+225",
  "Jamaica": "+1876",
  "Japan": "+81",
  "Jordan": "+962",
  "Kazakhstan": "+7",
  "Kenya": "+254",
  "Kuwait": "+965",
  "Lebanon": "+961",
  "Liechtenstein": "+423",
  "Lithuania": "+370",
  "Luxembourg": "+352",
  "Malaysia": "+60",
  "Malta": "+356",
  "Mexico": "+52",
  "Monaco": "+377",
  "Mongolia": "+976",
  "Morocco": "+212",
  "Myanmar": "+95",
  "Namibia": "+264",
  "Nepal": "+977",
  "Netherlands": "+31",
  "New Zealand": "+64",
  "Nigeria": "+234",
  "Norway": "+47",
  "Oman": "+968",
  "Pakistan": "+92",
  "Panama": "+507",
  "Papua New Guinea": "+675",
  "Paraguay": "+595",
  "Peru": "+51",
  "Philippines": "+63",
  "Poland": "+48",
  "Portugal": "+351",
  "Qatar": "+974",
  "Romania": "+40",
  "Russia": "+7",
  "San Marino": "+378",
  "Saudi Arabia": "+966",
  "Serbia": "+381",
  "Singapore": "+65",
  "Slovakia": "+421",
  "Slovenia": "+386",
  "South Africa": "+27",
  "South Korea": "+82",
  "Spain": "+34",
  "Sri Lanka": "+94",
  "Sweden": "+46",
  "Switzerland": "+41",
  "Thailand": "+66",
  "Trinidad and Tobago": "+1868",
  "Tunisia": "+216",
  "Turkey": "+90",
  "UAE": "+971",
  "Ukraine": "+380",
  "United Kingdom": "+44",
  "United States": "+1",
  "Uruguay": "+598",
  "Uzbekistan": "+998",
  "Vatican City": "+39",
  "Venezuela": "+58",
  "Vietnam": "+84",
  "Zimbabwe": "+263",
};
