import mongoose from "mongoose";

const requestSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    user: {
      _id: mongoose.Schema.Types.ObjectId,
      fullName: String,
      username: String,
      email: String,
      mobile: String,
      nationalOrPassportNumber: String,
      birthDate: String,
      idImage: String,
      licenseImage: String,
      criminalRecord: String,
      status: String,
      profilePicture: String,
    },
    source: {
      street: String,
      building: String,
      city: String,
      district: String,
      governorate: String,
      postalCode: String,
      country: String,
      latitude: Number,
      longitude: Number,
    },
    destination: {
      street: String,
      building: String,
      city: String,
      district: String,
      governorate: String,
      postalCode: String,
      country: String,
      latitude: Number,
      longitude: Number,
    },
    from: {
      street: String,
      building: String,
      city: String,
      district: String,
      governorate: String,
      postalCode: String,
      country: String,
      latitude: Number,
      longitude: Number,
    },
    to: {
      street: String,
      building: String,
      city: String,
      district: String,
      governorate: String,
      postalCode: String,
      country: String,
      latitude: Number,
      longitude: Number,
    },
    items: [
      {
        item: String,
        name: String,
        category: String,
        weight: String,
        dimensions: String,
        quantity: Number,
        note: String,
        media: [
          {
            url: String,
            existing: Boolean,
          },
        ],
        services: {
          canBeAssembledDisassembled: Boolean,
          assemblyDisassemblyHandler: String,
          packaging: Boolean,
          assemblyDisassembly: Boolean,
        },
      },
    ],
    estimatedCost: String,
    primaryCost: String,
    cost: String,
    startTime: Date,
    requestStatus: {
      type: String,
      enum: [
        "Pending",
        "Accepted",
        "Rejected",
        "Assigned to Company",
        "In Progress",
        "Completed",
        "Cancelled",
        "Action needed",
      ],
      default: "Pending",
    },
    deliveryStatus: {
      type: String,
      enum: [
        "Pending",
        "Picked Up Source",
        "Warehouse Source Received",
        "In Transit",
        "Warehouse Destination Received",
        "Shipment Deliver",
        "Delivered",
        "Failed",
      ],
      default: "Pending",
    },
    deliveryType: String,
    comment: String,
    sourceWarehouse: {
      id: String,
      name: String,
      address: String,
      city: String,
      country: String,
      coordinates: {
        latitude: Number,
        longitude: Number,
      },
      assignedAt: Date,
    },
    destinationWarehouse: {
      id: String,
      name: String,
      address: String,
      city: String,
      country: String,
      coordinates: {
        latitude: Number,
        longitude: Number,
      },
      assignedAt: Date,
    },
    sourcePickupMode: {
      type: String,
      enum: ["Delegate", "Self"],
    },
    destinationPickupMode: {
      type: String,
      enum: ["Delegate", "Self"],
    },
    requestStatusHistory: [
      {
        status: String,
        timestamp: Date,
        reason: String,
      },
    ],
    deliveryStatusHistory: [
      {
        status: String,
        timestamp: Date,
        reason: String,
      },
    ],
    costOffers: [
      {
        cost: Number,
        company: {
          id: String,
          name: String,
          phoneNumber: String,
          email: String,
          address: String,
          rate: String,
        },
        comment: String,
        selected: Boolean,
        status: {
          type: String,
          enum: ["pending", "accepted", "rejected"],
        },
        createdAt: Date,
        offeredAt: Date,
      },
    ],
    activityHistory: [
      {
        timestamp: Date,
        action: String,
        description: String,
        companyName: String,
        companyRate: String,
        cost: Number,
        details: String,
      },
    ],
    assignedCompanyId: String,
    selectedCompany: {
      id: String,
      name: String,
      rate: String,
      cost: Number,
    },
    assignedWarehouseId: String,
    assignedWarehouse: mongoose.Schema.Types.Mixed,
    deliveryFlow: [String],
    deliveryCompletedStatuses: [String],
    orderFlow: [String],
    orderCompletedStatuses: [String],
    rejectedByCompanies: [String],
  },
  { timestamps: true },
);

export const Request =
  mongoose.models.Request || mongoose.model("Request", requestSchema);
